# Generated by Django 6.0.3 on 2026-04-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'success'), (2, 'error')], default=0)),
                ('date_send', models.DateTimeField(null=True)),
                ('date_error', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.CreateModel(
            name='OrderAmazonFake',
            fields=[
                ('ordermarketplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.ordermarketplace')),
            ],
            bases=('orders.ordermarketplace',),
        ),
        migrations.AddField(
            model_name='ordermarketplace',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
