# Generated by Django 6.0.3 on 2026-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_remove_order_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders_product', through='orders.OrderProduct', to='orders.product'),
        ),
    ]
