# Generated by Django 6.0.3 on 2026-04-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAliexpressFake',
            fields=[
                ('ordermarketplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.ordermarketplace')),
            ],
            bases=('orders.ordermarketplace',),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderProduct', to='orders.product'),
        ),
    ]
