# Generated by Django 6.0.3 on 2026-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderaliexpressfake_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermarketplace',
            name='url_marketplace',
            field=models.URLField(null=True),
        ),
    ]
