# Generated by Django 6.0.3 on 2026-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordermarketplace_url_marketplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermarketplace',
            old_name='date_send',
            new_name='date_success',
        ),
        migrations.AddField(
            model_name='ordermarketplace',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
