# Generated by Django 6.0.3 on 2026-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_date_send_ordermarketplace_date_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermarketplace',
            name='api_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
