# Generated by Django 6.0.3 on 2026-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordermarketplace_api_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermarketplace',
            name='api_call_error_msg',
            field=models.TextField(blank=True),
        ),
    ]
