# Generated by Django 6.0.3 on 2026-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordermarketplace_api_call_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermarketplace',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
